version: '3.8'

volumes:
  pg_data:
  static:
  media:
  data:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: ilxpirate/foodgram_backend:latest
    volumes:
      - data:/app/data/
      - static:/backend_static
      - media:/media
    depends_on:
      - db
    env_file: .env

  frontend:
    image: ilxpirate/foodgram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - backend

  gateway:
    image: ilxpirate/foodgram_gateway:latest
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles/
      - media:/media
