version: '3.8'
services:

volumes:
  pg_data:
  static:
  media:
  data:

  services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: ilxpirate/foodgram_backend:latest
    restart: always
    volumes:
      - data:/app/data/
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db
    env_file: .env

  frontend:
    image: ilxpirate/foodgram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - backend

  gateway:
    image: ilxpirate/foodgram_gateway:latest
    ports:
      - 9000:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - frontend
