version: '3'

services:

  db:
    container_name: db
    image: postgres:13.0-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/
    restart: always

  backend:
    container_name: backend
    image: ilxpirate/foodgram_backend:latest
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db
    restart: always

  frontend:
    container_name: frontend
    image: ilxpirate/foodgram_frontend:latest
    volumes:
      - static:/frontend_static
    restart: on-failure

  gateway:
    container_name: nginx
    image: nginx:1.19.3
    ports:
      - 8000:80
    volumes:
      - ../infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/staticfiles/
      - media:/var/html/media/
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  pg_data:
  static:
  media: